### ISSUE TITLE
GPU infer time is slow than CPU infer time

### ISSUE THREAD

**Issue by maozhiqiang** [mozilla/FFTNet#1]
hi! I used run_time_test.py to test time! 
> Avg time per step inference on CPU: 0.002576863145828247
> Avg time per step inference on GPU: 0.003681471061706543

**Comment by erogol** [comment]
It is normal. Since there are only ~30 matrix operations and using GPU requires data to be transfered to GPU for each time step. However, run_time_test.py creates random matrices for once and use them for each iteration. Then the other reason might be using linear layers for inference by reshaping weights. I remember, values were better for conv layers in use but it was still slower compared to CPU. One last reason might be that inference uses a single instance each time, no batching, that might lead CPU be faster. 

These are my educated guesses. If you have something to share pls do so .

**Comment by maozhiqiang** [comment]
thanks for your reply! I'm still reading the paper ！
